default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: school_api_development
test:
  <<: *default
  database: school_api_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
